"""Initial migration.

Revision ID: 01edf6a3b707
Revises: 
Create Date: 2024-01-12 01:29:56.194330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01edf6a3b707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_term', sa.String(length=40), nullable=False),
    sa.Column('state_symbol', sa.String(length=2), nullable=False),
    sa.Column('positive_percent', sa.Float(), nullable=False),
    sa.Column('negative_percent', sa.Float(), nullable=False),
    sa.Column('neutral_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_sentiment')
    # ### end Alembic commands ###
